name: Typecheck
description: Run TypeScript typechecking for Node.js / Next.js projects

inputs:
    node_version:
        description: 'Node.js version'
        required: false
        default: '22.18.0'

    typecheck_command:
        description: "The typecheck script to run (e.g., 'typecheck', 'tsc', 'check:types')"
        required: false
        default: ''

runs:
    using: 'composite'
    steps:
        - name: Checkout repository
          uses: actions/checkout@v6

        - name: Set up Node.js environment
          uses: actions/setup-node@v6
          with:
              node-version: ${{ inputs.node_version }}
              cache: npm

        - name: Install dependencies
          shell: bash
          run: npm install

        - name: Run typecheck command
          shell: bash
          run: |
              cmd="${{ inputs.typecheck_command }}"

              if [ -z "$cmd" ]; then
                echo "No typecheck_command provided. Skipping typechecking."
                exit 0
              fi

              if npm pkg get scripts.$cmd | grep -vq null; then
                echo "Running $cmd..."
                npm run "$cmd"
              else
                echo "Skipping $cmd — script '$cmd' not found in package.json"
              fi
