name: Node Lint
description: Run configurable Node.js lint commands (ESLint, Stylelint, etc.) with optional Next.js cache

inputs:
  node_version:
    description: "Node.js version"
    required: false
    default: "22.18.0"

  nextjs:
    description: "Enable Next.js cache (.next/cache)"
    required: false
    default: "false"

  lint_commands:
    description: "List of package.json scripts to run"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node_version }}
        cache: npm

    - name: Cache node modules and Next.js build cache
      if: ${{ inputs.nextjs == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Run configured lint commands
      shell: bash
      run: |
        cmds="${{ inputs.lint_commands }}"

        # No commands provided, skip early
        if [ -z "$cmds" ]; then
          echo "No lint_commands provided. Skipping linting."
          exit 0
        fi

        echo "Running lint commands:"
        echo "$cmds"

        # Loop through each command
        while IFS= read -r cmd; do
          [ -z "$cmd" ] && continue

          # Check script existence
          if npm pkg get scripts.$cmd | grep -vq null; then
            echo "> $cmd"
            npm run "$cmd"
          else
            echo "> Skipping $cmd — script not found"
          fi
        done <<< "$cmds"
