name: Node Setup
description: |
  Set up a Node.js environment with optional cache and version-file support.

outputs:
  node_version_used:
    description: "Node.js version detected after setup"
    value: ${{ steps.node-version.outputs.version }}

inputs:
  node_version:
    description: "Node.js version (e.g. 22.18.0)"
    required: false
    default: "22.18.0"

  node_version_file:
    description: "File containing the Node.js version (e.g. .nvmrc, .node-version)"
    required: false
    default: ""

  cache:
    description: "Package manager to cache (npm, yarn, pnpm). Set blank to disable."
    required: false
    default: "npm"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        node-version-file: ${{ inputs.node_version_file }}
        cache: ${{ inputs.cache }}

    - name: Record Node.js version
      id: node-version
      shell: bash
      run: echo "version=$(node --version)" >> "$GITHUB_OUTPUT"
